### ISSUE TITLE
Implementation main menu design in QT

### ISSUE THREAD

**Issue by rezaqomy** [rezaqomy/quse#2]
Task for @JavadMoghaddas

- [x] crate branch Implementation design menu
- [x] create struct of design
- [x] add style to the struct
- [ ] #6

**Comment by JavadMoghaddas** [comment]
پلیز ورایت این فارسی 
اند اکسپلین ایت 
آی دونت آندرستند اینگلیش

**Comment by rezaqomy** [comment]
> پلیز ورایت این فارسی اند اکسپلین ایت آی دونت آندرستند اینگلیش

چرا کالبریتور نیستی
